$borderTop = rgba(8be9fdee)
$borderBottom = rgba(ffffffee)
$inactiveBorder = rgba(0A142888)

general {
    col.active_border = $borderTop $borderBottom 180deg
    col.inactive_border = $inactiveBorder
}

group {
    col.border_active = $borderTop $borderBottom 180deg
}
