# This file is not a full hyprland configuration.
# It is intended to be included in your main hyprland.conf.


general {
    col.active_border = rgba(8be9fdee) rgba(ffffffee) 180deg
    col.inactive_border = rgba(0A142888)
}

group {
    col.border_active = rgba(8be9fdee) rgba(ffffffee) 180deg
}
