# Extra autostart processes
# exec-once = uwsm-app -- my-service

# chromium -> workspace 2
#exec-once = [workspace 2 silent] chromium
#exec-once = ~/.local/bin/adept-wallpaper

bind = SUPER, SPACE, exec, walker


# btop → workspace 4
exec-once = [workspace 4 silent] ghostty -e btop
