# Extra autostart processes
# exec-once = uwsm-app -- my-service

# chromium -> workspace 2
#exec-once = [workspace 2 silent] chromium

# btop → workspace 4
exec-once = [workspace 4 silent] ghostty -e btop


