# Walker
bind = SUPER, SPACE, exec, walker

# Application bindings
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(syna-cmd-terminal-cwd)"
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER SHIFT, B, Browser, exec, syna-launch-browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, syna-launch-browser --private
bindd = SUPER SHIFT, M, Music, exec, syna-launch-or-focus spotify
bindd = SUPER SHIFT, N, Editor, exec, syna-launch-editor
bindd = SUPER SHIFT, T, Activity, exec, syna-launch-tui btop
bindd = SUPER SHIFT, D, Docker, exec, syna-launch-tui lazydocker
bindd = SUPER SHIFT, G, Signal, exec, syna-launch-or-focus ^signal$ "uwsm-app -- signal-desktop"
bindd = SUPER SHIFT, O, Obsidian, exec, syna-launch-or-focus ^obsidian$ "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"
bindd = SUPER SHIFT, W, Typora, exec, uwsm-app -- typora --enable-wayland-ime
bindd = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- 1password

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
bindd = SUPER SHIFT, A, ChatGPT, exec, syna-launch-webapp "https://chatgpt.com"
#bindd = SUPER SHIFT ALT, A, Grok, exec, syna-launch-webapp "https://grok.com"
#bindd = SUPER SHIFT, C, Calendar, exec, syna-launch-webapp "https://app.hey.com/calendar/weeks/"
#bindd = SUPER SHIFT, E, Email, exec, syna-launch-webapp "https://app.hey.com"
bindd = SUPER SHIFT, Y, YouTube, exec, syna-launch-webapp "https://youtube.com/"
bindd = SUPER SHIFT ALT, G, WhatsApp, exec, syna-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
bindd = SUPER SHIFT CTRL, G, Google Messages, exec, syna-launch-or-focus-webapp "Google Messages" "https://messages.google.com/web/conversations"
#bindd = SUPER SHIFT, P, Google Photos, exec, syna-launch-or-focus-webapp "Google Photos" "https://photos.google.com/"
#bindd = SUPER SHIFT, X, X, exec, syna-launch-webapp "https://x.com/"
#bindd = SUPER SHIFT ALT, X, X Post, exec, syna-launch-webapp "https://x.com/compose/post"

# Screenshots with SHIFT + Delete
bindd = SHIFT, Delete, Screenshot of region, exec, ~/.local/bin/rice/syna-cmd-screenshot
bindd = SHIFT CTRL, Delete, Screenshot of window, exec, ~/.local/bin/rice/syna-cmd-screenshot window
bindd = SHIFT ALT, Delete, Screenshot of display, exec, ~/.local/bin/rice/syna-cmd-screenshot output

# Apps
bind = SUPER, G, exec, [workspace 5] gamescope --backend sdl -W 2560 -H 1440 -r 165 --adaptive-sync --steam --force-grab-cursor -f

# Custom Keybindings
#bind = SUPER, B, exec, firefox

