# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale

# Optimized for retina-class 2x displays, like 13" 2.8K, 27" 5K, 32" 6K.
env = GDK_SCALE,1
#monitor=DP-1,2560x1440@165,0x0,1
#monitor=DP-2,1920x1080@165,auto,1

# Generate profile based on boot entry
#exec-once = ~/.config/hypr/scripts/select-monitor-profile.sh

# Load generated layout
#source = ~/.config/hypr/monitors.generated.conf


monitor = desc:Acer Technologies XB271HU,2560x1440@165,0x0,1
#monitor=DP-3,1920x1080@165,2560x0,1,transform,3,vrr,0
monitor = desc:HKC OVERSEAS LIMITED 24E3,1920x1080@165,2560x0,1




windowrulev2 = workspace 2 silent, class:^(steam_app_.*)$


workspace = 1, monitor:desc:Acer Technologies XB271HU, default:true
workspace = 2, monitor:desc:HKC OVERSEAS LIMITED 24E3, default:true
workspace = 3, monitor:desc:Acer Technologies XB271HU
workspace = 4, monitor:desc:HKC OVERSEAS LIMITED 24E3
workspace = 5, monitor:desc:Acer Technologies XB271HU

# Good compromise for 27" or 32" 4K monitors (but fractional!)
# env = GDK_SCALE,1.75
# monitor=,preferred,auto,1.6

# Straight 1x setup for low-resolution displays like 1080p or 1440p
# env = GDK_SCALE,1
# monitor=,preferred,auto,1

# Example for Framework 13 w/ 6K XDR Apple display
# monitor = DP-5, 6016x3384@60, auto, 2
# monitor = eDP-1, 2880x1920@120, auto, 2
