# =========================
# Window rules (user)
# Hyprland 0.53+ (new syntax)
# =========================

# eww syna-dashboard - no compositor rounding (use CSS instead)
windowrule = rounding 0, match:class ^(eww)$


# Chromium → workspace 2 (runtime/manual launches)
#windowrule = workspace 2 silent, match:initialClass ^(chromium|google-chrome|brave)$

# btop → workspace 4
#windowrule = workspace 4 silent, match:class ^(ghostty)$, match:title ^(btop)

# Waydroid - fullscreen on primary monitor
windowrule {
    name = waydroid
    match:class = ^(Waydroid)$
    monitor = desc:Acer Technologies XB271HU
    size = 2560 1440
    center = on
    fullscreen = on
    fullscreen_state = 2 2
    no_blur = on
    idle_inhibit = always
}

xwayland {
  force_zero_scaling = true
}
