# If not running interactively, don't do anything (leave this at the top of this file)
[[ $- != *i* ]] && return

# Default aliases and functions
# (customize below, or add to ~/.bashrc)

# Add your own exports, aliases, and functions here.
#
# Make an alias for invoking commands you use constantly
# alias p='python'
